### ISSUE TITLE
Snapped smoke tests failing since core20 switch

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir-test-tools#26]
Most of the test runs in the lab started failing, and the only relevant error I found was this:

```
/bin/bash: /snap/mir-test-tools/3867/lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /bin/bash)
```

Looks like we're missing bash inside the snap. Or maybe we could avoid bash and use a simpler shell?

**Comment by Saviq** [comment]
#25 fixes this AFAICT.

**Comment by AlanGriffiths** [comment]
Hmm...
```plain
$ mir-test-tools.smoke-test 
Segmentation fault (core dumped)
```

**Comment by Saviq** [comment]
> Hmm...
> 
> ```
> $ mir-test-tools.smoke-test 
> Segmentation fault (core dumped)
> ```

Yes, symptom of the same problem, AFAICT.

**Comment by Saviq** [comment]
Invalid, see #25 for why.

**Comment by Saviq** [comment]
Sorry, this wasn't invalid, per se. The problem was in the build environment, apparently it needs to be "Ubuntu Core 16" for Launchpad to pick up the `base:` from `snapcraft.yaml`.
